name: Generate Snake
on:
  schedule:
    - cron: "0 0 * * *"  
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk/svg-only@v3
        with:
          github_user_name: iamnguyenvu
          outputs: |
            dist/snake.svg
            dist/snake-dark.svg?palette=github-dark
            dist/snake-sky.svg?color_snake=%2300BFFF&color_dots=%23e6f3ff,%23bfe1ff,%238fc7ff,%235eabff,%232e8bff

      - name: Deploy to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
